project_id = "qocduqtfbsevnhlgsfka"

[functions.test-attom]
verify_jwt = false

[functions.auto-fetch-property-data]
verify_jwt = false

[functions.fetch-attom-market-data]
verify_jwt = false

[functions.fetch-property-data]
verify_jwt = false

[functions.send-price-change-notification]
verify_jwt = false

[functions.send-new-match-notification]
verify_jwt = false
