project_id = "qocduqtfbsevnhlgsfka"

[functions.test-attom]
verify_jwt = false

[functions.auto-fetch-property-data]
verify_jwt = false

[functions.fetch-attom-market-data]
verify_jwt = false

[functions.fetch-property-data]
verify_jwt = false

[functions.fetch-neighborhood-data]
verify_jwt = false

[functions.fetch-walkscore]
verify_jwt = false

[functions.update-listing-statuses]
verify_jwt = false

[functions.send-price-change-notification]
verify_jwt = false

[functions.send-new-match-notification]
verify_jwt = false

[functions.send-listing-share]
verify_jwt = false

[functions.get-city-zips]
verify_jwt = false

[functions.send-showing-request-email]
verify_jwt = false

[functions.social-preview]
verify_jwt = false

[functions.send-verification-submitted]
verify_jwt = false

[functions.send-agent-approval-email]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false

[functions.delete-users]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false
